### ISSUE TITLE
🐛 [Bug Report] - TK, Kael, Staff of Disintegration

### ISSUE THREAD

**Issue by Crushhymn** [DramatimeWoW/TBC5ManTracker#42] opened 2019-08-21 19:47 UTC
# Decription: # 
The Legendary staff "Staff of Disintegration" that you can obtain during the TK Kael'thas fight will give a buff when you activate it stating "Use: Places a mental protection field on friendly targets withing 30 yards, granting immunity to Stun, Silence, and Disorient effects".
During our raid tonight, we used 2 casters with staff, one at range close quarters to our hunter and healer, while I was standing 8-10 ft from our tank.
We were running comms which is how we noticed.

# How it works: #
Tank was getting staff buff as expected, he was however hit with disorient in 4 different attempts, which caused us to wipe as boss runs loose.

# How it should work: #
Buff should grant immunity to disorient.

# Source - You need to provide a source as evidence: #
Unfortunately we were not able to catch a screenshot of it happening, but all 5 members of our group are witnesses.

# Additional Information: #
We will attempt to gain a screenshot on next try, but we wanted to open this in case someone else experienced the same thing.
We have all killed him several times, and we always use the staff in cast macro to make sure everyone has a fresh application.

**Comment by oldspices** [comment] 2019-08-24 20:35
we were wiping to this too

**Comment by BlessedPinkie** [comment] 2019-08-26 17:51
Thoroughly tested and everything seems to be working for both the player with the staff and the players in the spell radius. If you're counting the fear as something that should be avoided, it's a flee mechanic which isn't something mitigated by the staffs spell.

**Comment by BlessedPinkie** [comment] 2019-08-27 00:53
Going to close this for now, please feel free to prove my findings wrong if you are adament there is still an issue.

**Comment by oldspices** [comment] 2019-08-27 06:37
For us it was a disorient effect, we were all in range + had the staff buff up, we just kept attempting boss until it didn't do that... then we downed him.  2 "bugs" and 1 kill.

**Comment by BlessedPinkie** [comment] 2019-08-27 11:19
Which effects are you talking about because I can't reproduce any problems with effects that are countered by the staffs aura. Can you give me a spell name?

**Comment by Crushhymn** [comment] 2019-08-27 12:55
It was also a disorient for us, it happened on Kael so it is one of his spells, but I were unable to find a disorient in his spellbook.

**Comment by Crushhymn** [comment] 2019-08-27 16:06
This is the only disorient I can find on Kael himself. 
Arcane Disruption – 1750-2250 Arcane damage and a 10-second disorient to every raid member, 20 sec cooldown, can be removed with PvP Trinket

**Comment by BlessedPinkie** [comment] 2019-08-27 21:02
Ah ok I'll double check this spell.

**Comment by BlessedPinkie** [comment] 2019-08-28 23:33
Re-checked, the staff mitigates Arcane Disruption for both the players with the staff and surrounding players. At this point I can only assume it's player error, misjuding the range or LOS, who knows. I've double checked all the spells that the staff should mitigate and so far not one test has successfully applied the debuff to a player with the staff buff

Closing.

**Closed as completed by BlessedPinkie** 2019-08-28 23:33 UTC
Labels: New Bug - Needs Replication, Lacks Confirmation or Evidence

**Comment by Crushhymn** [comment] 2019-08-29 05:09
I can say for sure that we did not misjudge range. I was standing maximum of 10 ft away, with staff included in my lightning bolt cast.
Thank you for looking into this though, as I said, we will try to get a screen.
